### ISSUE TITLE
Potential browser incompatibility

### ISSUE THREAD

**Issue by NicoleWebb** [joyceykao/advlanding#10]
Using Safari the text is jumbled in the workflows section.

**Comment by evaherbst** [comment]
I also have this sometimes when I open it on chrome. The workflows aren't surrounded by boxes and are all listed on top of one another. Refreshing solves the issue

**Comment by joyceykao** [comment]
@evaherbst @NicoleWebb, Can you try again to see if this occurs still?

**Comment by evaherbst** [comment]
I checked and it looks great for me! even if I make the browser window smaller

**Comment by NicoleWebb** [comment]
Looks awesome! Thanks so much!

**Comment by joyceykao** [comment]
Fixed the description overflow box issue on workflow card that Eva and I found today with xl displays.
