### ISSUE TITLE
add GRC, PIM, and IEM logos to website

### ISSUE THREAD

**Issue by evaherbst** [joyceykao/advlanding#14]
Please add the PIM, the GRC, and the IEM logos to the bottom of the home page of the landing website.

Logo images with black backgrounds can be found here: https://drive.google.com/drive/u/0/folders/1R_OPmNs6wLolQaSJlk0ScIOf8YH_VOO3

Thank  you!

**Comment by joyceykao** [comment]
Done and linked them to the respective pages as well.
