### ISSUE TITLE
title of repository goes outside of box if I don't use a maximized window 

### ISSUE THREAD

**Issue by evaherbst** [joyceykao/advlanding#16]
![image](https://user-images.githubusercontent.com/31034865/108508370-ff250880-72bb-11eb-83b4-30616151a4eb.png)

**Comment by joyceykao** [comment]
@evaherbst I shrunk the text so now the title has to be pretty darn long to mess with the formatting. Let me know what you think.

**Comment by evaherbst** [comment]
Looks great!
