### ISSUE TITLE
Social Media (FB/Twitter) meta tags

### ISSUE THREAD

**Issue by joyceykao** [joyceykao/advlanding#3]
to display a preview properly when posting links on FB/Twitter/Slack, etc.

**Comment by evaherbst** [comment]
description: a virtual hub to share finite element analysis workflows for biomechanics research

**Comment by evaherbst** [comment]
image: use the rainbow logo image from the main page

**Comment by Dylan-Bastiaans** [comment]
title: Finite Element Zürich (FEZ) 

Do we need anything else like "meeting" or just FEZ alone would be enough? I guess the latter as we want to use this website later on too and not just for the meeting.

**Comment by joyceykao** [comment]
@evaherbst @Dylan-Bastiaans @NicoleWebb 

I need slightly different sized images for Facebook and Twitter. As of now, it does not look good. :( See Twitter card below
<img width="461" alt="Screen Shot 2021-02-08 at 8 52 07 PM" src="https://user-images.githubusercontent.com/52547142/107278423-165f2d00-6a56-11eb-873a-1ec2a404d536.png">
 

Guidelines for FB image:
It should be at least 600×315 pixels, but 1200×630 or larger is preferred (up to 5MB). Stay close to a 1.91:1 aspect ratio to avoid cropping. NEEDS TO BE IN JPEG FORMAT.
 
 Guidelines for Twitter image:
 Images for this Card should be at least 280px in width, and at least 150px in height. Image must be less than 1MB in size. CAN BE JPEG OR PNG.

**Comment by joyceykao** [comment]
> title: Finite Element Zürich (FEZ)
> 
> Do we need anything else like "meeting" or just FEZ alone would be enough? I guess the latter as we want to use this website later on too and not just for the meeting.

This is for your FEZ website...the meeting website is something else.

**Comment by evaherbst** [comment]
> > title: Finite Element Zürich (FEZ)
> > Do we need anything else like "meeting" or just FEZ alone would be enough? I guess the latter as we want to use this website later on too and not just for the meeting.
> 
> This is for your FEZ website...the meeting website is something else.

Yes agreed with Joyce

**Comment by NicoleWebb** [comment]
Are these okay?! I don't know if I resized them correctly. I just used the suggested height and width in pixels.
![Twitter_final_FEZ](https://user-images.githubusercontent.com/71884495/107485812-8ec40c00-6b84-11eb-9b9e-2c44ac13d9fe.jpg)


![Facebook_FEZ_final](https://user-images.githubusercontent.com/71884495/107485250-d26a4600-6b83-11eb-9cfb-684bee69ab59.jpg)

**Comment by NicoleWebb** [comment]
> @evaherbst @Dylan-Bastiaans @NicoleWebb
> 
> I need slightly different sized images for Facebook and Twitter. As of now, it does not look good. :( See Twitter card below
> <img alt="Screen Shot 2021-02-08 at 8 52 07 PM" width="461" src="https://user-images.githubusercontent.com/52547142/107278423-165f2d00-6a56-11eb-873a-1ec2a404d536.png">
> 
> Guidelines for FB image:
> It should be at least 600×315 pixels, but 1200×630 or larger is preferred (up to 5MB). Stay close to a 1.91:1 aspect ratio to avoid cropping. NEEDS TO BE IN JPEG FORMAT.
> 
> Guidelines for Twitter image:
> Images for this Card should be at least 280px in width, and at least 150px in height. Image must be less than 1MB in size. CAN BE JPEG OR PNG.

I tried to resize, let me know if this worked!
Thanks!

![Facebook_FEZ_final](https://user-images.githubusercontent.com/71884495/107485966-c3d05e80-6b84-11eb-9844-21ddb7aea59d.jpg)
![Twitter_final_FEZ](https://user-images.githubusercontent.com/71884495/107485976-c6cb4f00-6b84-11eb-84f1-cbdb76118db2.jpg)

**Comment by NicoleWebb** [comment]
> @evaherbst @Dylan-Bastiaans @NicoleWebb
> 
> I need slightly different sized images for Facebook and Twitter. As of now, it does not look good. :( See Twitter card below
> <img alt="Screen Shot 2021-02-08 at 8 52 07 PM" width="461" src="https://user-images.githubusercontent.com/52547142/107278423-165f2d00-6a56-11eb-873a-1ec2a404d536.png">
> 
> Guidelines for FB image:
> It should be at least 600×315 pixels, but 1200×630 or larger is preferred (up to 5MB). Stay close to a 1.91:1 aspect ratio to avoid cropping. NEEDS TO BE IN JPEG FORMAT.
> 
> Guidelines for Twitter image:
> Images for this Card should be at least 280px in width, and at least 150px in height. Image must be less than 1MB in size. CAN BE JPEG OR PNG.

![LOGO_facebook-01](https://user-images.githubusercontent.com/71884495/107499222-f97d4380-6b94-11eb-965a-6a4fef0ad64f.jpg)
![Twitter_FEZ-01](https://user-images.githubusercontent.com/71884495/107500881-faaf7000-6b96-11eb-8bf0-68e67c0a5f15.jpg)

**Comment by evaherbst** [comment]
I double checked the dimensions of Nicole's images, looks good to me!

**Comment by NicoleWebb** [comment]
> I double checked the dimensions of Nicole's images, looks good to me!

I tried to fix the Twitter one (you said it was slightly stretched). 

![Twitter_FEZ-02](https://user-images.githubusercontent.com/71884495/107521233-95697800-6bb2-11eb-89d1-b433e1757a7e.jpg)

**Comment by joyceykao** [comment]
Swapped out logo and it's at least no longer cut off.
