### ISSUE TITLE
Need additional text & info

### ISSUE THREAD

**Issue by joyceykao** [joyceykao/advlanding#6]
Still need

- [x] descriptions for 'Workflows' page
- [x] Keywords for each founder --> do we need this?
- [x] What highlight to put in highlights? Image and link.
- [x] Contact us email, who's email should I send it to?

**Comment by NicoleWebb** [comment]
my keywords: pelvic functional morphology, bipedalism, birth

**Comment by NicoleWebb** [comment]
contact email: fezurich@gmail.com

**Comment by evaherbst** [comment]
my keywords: skull functional morphology, biomechanical modeling

not sure if I should add programs or anything

**Comment by NicoleWebb** [comment]
Here is a favicon logo. Let me know if it is too pixelated it is currently 32x32 pixels.

![LogoFEZball](https://user-images.githubusercontent.com/71884495/105194505-f2d15280-5b39-11eb-97b3-a066c3644c55.jpg)

**Comment by evaherbst** [comment]
Looks good to me (even if I zoom out a bit to make it the same size as the favicons on the tabs I currently have open).

**Comment by joyceykao** [comment]
The favicon has been added as well as the email.

**Comment by joyceykao** [comment]
Added the keywords for @evaherbst and @NicoleWebb 

I just need the two items left at the top of this issue. What to put in highlights and what to put in the workflow description (which the latter is likely just waiting on further implementation and instructions from me).

**Comment by evaherbst** [comment]
Highlight card: let's keep the current image and we can put "Finite Element Analysis Lecture Series and Workshop - Online March 17th and 18th" and a link to the b2match page. We don't have one yet (or I can't find it yet) because we haven't published it yet. But we will very soon

**Comment by evaherbst** [comment]
**Workflow description:**
Our goal is to enable anyone, regardless of institution, to be able to learn FEA or to try out techniques and software (for example freeware alternatives. We created a [Github organisation](https://github.com/FEZ-Finite-Element-Zurich) for biomechanists to share their FEA workflows and code. Interested in contributing? Find more information [here](https://github.com/FEZ-Finite-Element-Zurich/FEZ-Main-Info/blob/master/README.md).

To create a community of FEA biomechanists across institutions and career stages, we created a Slack channel. This is a space for discussing ideas, software troubleshooting, sharing papers, and forming collaborations. [Join us!](https://join.slack.com/t/finiteelementzurich/shared_invite/zt-lx6ns6fb-_YBEaCm_tuOz_UfZzNRiwg)

**Comment by evaherbst** [comment]
> Highlight card: let's keep the current image and we can put "Finite Element Analysis Lecture Series and Workshop - Online March 17th and 18th" and a link to the b2match page. We don't have one yet (or I can't find it yet) because we haven't published it yet. But we will very soon

for this, we now have the b2match page link: https://fez2021.b2match.io/

**Comment by joyceykao** [comment]
added all the info above.
